spring.application.name=SubscriptionTracker

spring.datasource.url=jdbc:mysql://localhost:3306/SUBDB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Aditya&adi1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=subtrap-super-secret-key-change-in-prod-min-32-chars
app.jwt.expiration-ms=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adityaelle9969@gmail.com
spring.mail.password=bsaw hxcb pisf gnwl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

server.port=8080
logging.level.org.springframework.security=DEBUG
logging.level.com.aurionpro=DEBUG

logging.level.org.springframework.security=TRACE
spring.security.filter.dispatcher-types=REQUEST,ASYNC,ERROR

spring.task.scheduling.enabled=true

